export const all = state => state
export const states = state => state.states || {};
export const profiles = state => state.profiles || {};
export const indicators = state => state.indicators || {};
export const checkbox = state => state.checkbox || {};
export const themes = state => state.themes || {};
export const dnevnik = state => state.dnevnik || {};
export const periods = state => state.periods || {};
export const teachers = state => state.teachers || {};
export const classmates = state => state.classmates || {};
export const parents = state => state.parents || {};
export const admins = state => state.admins || {};
export const hteachers = state => state.hteachers || {};
export const schedules = state => state.schedules || {};
export const marks = state => state.marks || {};
export const journals = state => state.journals || {};
export const zvonki = state => state.zvonki || {};
export const newsSelec = state => state.news || {};
export const contactsSelec = state => state.contacts || {};